# Generated by Django 5.2.8 on 2026-01-18 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 6, 53, 34, 269979, tzinfo=datetime.timezone.utc)),
        ),
    ]
